Flight/Models/AirRoutes.cs
using System;
using System.ComponentModel.DataAnnotations;
namespace Flight.Models
{
    public class AirRoutes
    {
        public AirRoutes()
        {
        }

        public int ID { get; set; }
        public string From { get; set; }
        public string To { get; set; }
        public int Stops { get; set; }
        public int Price { get; set; }

        [Display(Name = "Departing Date"), DataType(DataType.Date)]
        public DateTime departing { get; set; }

        [Display(Name = "Arrival Date"), DataType(DataType.Date)]
        public DateTime arrival { get; set; }

        [Display(Name = "Seats Available"), DataType(DataType.Text)]
        public string seatsAvailable { get; set; }
    }
}

Flight/Controllers/AirRoutesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Flight.Models;

namespace Flight.Controllers
{
    public class AirRoutesController : Controller
    {
        private readonly FlightContext _context;

        public AirRoutesController(FlightContext context)
        {

            _context = context;
        }

        // GET: AirRoutes
        public async Task<IActionResult> Index()
        {
            return View(await _context.AirRoutes.ToListAsync());
        }

        // GET: AirRoutes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var airRoutes = await _context.AirRoutes
                .SingleOrDefaultAsync(m => m.ID == id);
            if (airRoutes == null)
            {
                return NotFound();
            }

            return View(airRoutes);
        }

        // GET: AirRoutes/Create
        public IActionResult Create()
        {
            return View();
        }

        public IActionResult List(String value)
        {

            if (value == "stops")
            {
                return View("List_stops");
            } else if(value == "seats" ) 
            {
                return View("List_seats");
            } else if (value == "price")
            {
                return View("List_price");
            }

            return View();

        }


        // POST: AirRoutes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,From,To,Stops,Price,departing,arrival,seatsAvailable")] AirRoutes airRoutes)
        {
            if (ModelState.IsValid)
            {
                _context.Add(airRoutes);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(airRoutes);
        }



        // GET: AirRoutes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var airRoutes = await _context.AirRoutes.SingleOrDefaultAsync(m => m.ID == id);
            if (airRoutes == null)
            {
                return NotFound();
            }
            return View(airRoutes);
        }

        // POST: AirRoutes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,From,To,Stops,Price,departing,arrival,seatsAvailable")] AirRoutes airRoutes)
        {
            if (id != airRoutes.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(airRoutes);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AirRoutesExists(airRoutes.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(airRoutes);
        }

        // GET: AirRoutes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var airRoutes = await _context.AirRoutes
                .SingleOrDefaultAsync(m => m.ID == id);
            if (airRoutes == null)
            {
                return NotFound();
            }

            return View(airRoutes);
        }

        // POST: AirRoutes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var airRoutes = await _context.AirRoutes.SingleOrDefaultAsync(m => m.ID == id);
            _context.AirRoutes.Remove(airRoutes);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool AirRoutesExists(int id)
        {
            return _context.AirRoutes.Any(e => e.ID == id);
        }
    }
}

Flight/Views/AirRoutes/Create.cshtml
@model Flight.Models.AirRoutes

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<h4>AirRoutes</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="From" class="control-label"></label>
                <input asp-for="From" class="form-control" />
                <span asp-validation-for="From" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="To" class="control-label"></label>
                <input asp-for="To" class="form-control" />
                <span asp-validation-for="To" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Stops" class="control-label"></label>
                <input asp-for="Stops" class="form-control" />
                <span asp-validation-for="Stops" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="departing" class="control-label"></label>
                <input asp-for="departing" class="form-control" />
                <span asp-validation-for="departing" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="arrival" class="control-label"></label>
                <input asp-for="arrival" class="form-control" />
                <span asp-validation-for="arrival" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="seatsAvailable" class="control-label"></label>
                <input asp-for="seatsAvailable" class="form-control" />
                <span asp-validation-for="seatsAvailable" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Flight/Views/AirRoutes/Delete.cshtml
@model Flight.Models.AirRoutes

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>AirRoutes</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.From)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.From)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.To)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.To)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Stops)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Stops)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.departing)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.departing)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.arrival)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.arrival)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.seatsAvailable)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.seatsAvailable)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ID" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Flight/Views/AirRoutes/Details.cshtml
@model Flight.Models.AirRoutes

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>AirRoutes</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.From)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.From)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.To)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.To)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Stops)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Stops)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.departing)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.departing)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.arrival)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.arrival)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.seatsAvailable)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.seatsAvailable)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.ID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Flight/Views/AirRoutes/Edit.cshtml
@model Flight.Models.AirRoutes

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<h4>AirRoutes</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ID" />
            <div class="form-group">
                <label asp-for="From" class="control-label"></label>
                <input asp-for="From" class="form-control" />
                <span asp-validation-for="From" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="To" class="control-label"></label>
                <input asp-for="To" class="form-control" />
                <span asp-validation-for="To" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Stops" class="control-label"></label>
                <input asp-for="Stops" class="form-control" />
                <span asp-validation-for="Stops" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="departing" class="control-label"></label>
                <input asp-for="departing" class="form-control" />
                <span asp-validation-for="departing" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="arrival" class="control-label"></label>
                <input asp-for="arrival" class="form-control" />
                <span asp-validation-for="arrival" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="seatsAvailable" class="control-label"></label>
                <input asp-for="seatsAvailable" class="form-control" />
                <span asp-validation-for="seatsAvailable" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Flight/Views/AirRoutes/Index.cshtml
@model IEnumerable<Flight.Models.AirRoutes>

@{
    ViewData["Title"] = "Index";
}

<h2>Index</h2>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
                <th>
                    @Html.DisplayNameFor(model => model.From)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.To)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Stops)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Price)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.departing)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.arrival)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.seatsAvailable)
                </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.From)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.To)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Stops)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Price)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.departing)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.arrival)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.seatsAvailable)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.ID">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.ID">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.ID">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

Flight/Views/AirRoutes/List.cshtml
Min: <input type="text" name="min">
Max: <input type="text" name="max">

Flight/Views/AirRoutes/List_price.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

Min Price: <input type="text" name="minprice">
Max Price: <input type="text" name="maxprice">

Flight/Views/AirRoutes/List_seats.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

Min Seats: <input type="text" name="minseats">
Max Seats: <input type="text" name="maxseats">

Flight/Views/AirRoutes/List_stops.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
Min Stops: <input type="text" name="minstops">
Max Stops: <input type="text" name="maxstops">

Flight/Views/AirRoutes/PartialViews.cshtml
@using (Html.BeginForm("PartialView", "AirRoutes", FormMethod.Get))
{

}